# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # HTTPS
  config.vm.network "forwarded_port", guest: 8443, host: 443
  # TURN via TCP
  config.vm.network "forwarded_port", guest: 1194, host: 1194
  # TURN via UDP
  config.vm.network "forwarded_port", guest: 1194, host: 1194, protocol: "udp"
  # Media streams
  for i in 32000..32079
    config.vm.network "forwarded_port", guest: i, host: i, protocol: "udp"
  end

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  # Install Docker on the VM and add the vagrant user to the docker group for ease of use
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get -yq install docker.io
    usermod -a -G docker vagrant
  SHELL
end
