name: Destroy all Resources
on:
  workflow_dispatch:
jobs:
  destroy:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - uses: pulumi/actions@v3
        with:
          work-dir: ./deploy
          command: destroy
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ADMIN_PASSWORD: ${{ secrets.GALENE_ADMIN_PASSWORD }}
          SSL_CERTIFICATE: ${{ secrets.GALENE_SSL_CERTIFICATE }}
          SSL_PRIVATE_KEY: ${{ secrets.GALENE_SSL_PRIVATE_KEY }}
